# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

arr_height = np.array(height)
arr_weight = np.array(weight)

result = arr_weight / (arr_height**2) * 730
print(result)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [17]:
random_matrix = np.random.randint(10, size=(3,3))
print(random_matrix)


[[2 2 0]
 [6 3 5]
 [9 5 1]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np




In [28]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

length = len(bs2017['SLG'])
print('Average of the 2017 slugging percentage Column: {}'.format(sum(bs2017['SLG']) / length))

length = len(bs2018['SLG'])
print('Average of the 2018 slugging percentage Column: {}'.format(sum(bs2018['SLG']) / length))

#Use this function to actually open the data inside of a NDArray

if (sum(bs2017['SLG']) / length) > (sum(bs2018['SLG']) / length):
                                    print ('2017 slugging percentage is better than 2018')
else:
    print('2018 slugging percentage is better than 2017')

Average of the 2017 slugging percentage Column: 0.39334782374941785
Average of the 2018 slugging percentage Column: 0.38750000335276125
2017 slugging percentage is better than 2018
